import re

# We map known names to high credits, and regular to 8.5
SQUADS = {
    "RCB": [
        ("Virat Kohli", "BAT", 10.0),
        ("Josh Hazlewood", "BOWL", 9.0),
        ("Swapnil Singh", "AR", 8.0),
        ("Bhuvneshwar Kumar", "BOWL", 9.0),
        ("Jacob Duffy", "BOWL", 8.5),
        ("Krunal Pandya", "AR", 8.5),
        ("Jitesh Sharma", "WK", 8.5),
        ("Venkatesh Iyer", "AR", 9.0),
        ("Phil Salt", "WK", 9.5),
        ("Rajat Patidar", "BAT", 9.0),
        ("Nuwan Thushara", "BOWL", 8.5),
        ("Romario Shepherd", "AR", 8.5),
        ("Tim David", "BAT", 8.5),
        ("Devdutt Padikkal", "BAT", 8.5),
        ("Yash Dayal", "BOWL", 8.5),
        ("Rasikh Salam", "BOWL", 8.0),
        ("Jordan Cox", "BAT", 8.0),
        ("Jacob Bethell", "BAT", 8.0),
        ("Vicky Ostwal", "BOWL", 8.0),
        ("Mangesh Yadav", "AR", 7.5),
        ("Suyash Sharma", "BOWL", 8.0),
        ("Vihaan Manoj Malhotra", "AR", 7.5),
        ("Abhinandan Singh", "BOWL", 7.5),
        ("Kanishk Chouhan", "AR", 7.5),
        ("Satvik Deswal", "BAT", 7.5)
    ],
    "SRH": [
        ("Harshal Patel", "BOWL", 9.0),
        ("Jaydev Unadkat", "BOWL", 8.5),
        ("David Payne", "BOWL", 8.5),
        ("Pat Cummins", "BOWL", 9.5),
        ("Heinrich Klaasen", "WK", 10.0),
        ("Travis Head", "BAT", 10.0),
        ("Liam Livingstone", "AR", 9.0),
        ("Ishan Kishan", "WK", 9.0),
        ("Kamindu Mendis", "AR", 8.5),
        ("Brydon Carse", "BOWL", 8.5),
        ("Zeeshan Ansari", "BOWL", 8.0),
        ("Abhishek Sharma", "AR", 9.5),
        ("Shivam Mavi", "BOWL", 8.5),
        ("Harsh Dubey", "AR", 8.0),
        ("Salil Arora", "WK", 7.5),
        ("Nitish Kumar Reddy", "AR", 9.0),
        ("Amit Kumar", "AR", 7.5),
        ("Praful Hinge", "BOWL", 7.5),
        ("Smaran Ravichandran", "BAT", 7.5),
        ("Eshan Malinga", "BOWL", 8.0),
        ("Sakib Hussain", "BOWL", 7.5),
        ("Aniket Verma", "BAT", 7.5),
        ("Shivang Kumar", "BAT", 7.5),
        ("Krains Bhaveshbhai Fuletra", "BOWL", 7.5),
        ("Omkar Tarmale", "BOWL", 7.5)
    ],
    "MI": [
        ("Rohit Sharma", "BAT", 10.0),
        ("Trent Boult", "BOWL", 9.5),
        ("Suryakumar Yadav", "BAT", 10.0),
        ("Quinton de Kock", "WK", 9.5),
        ("Mitchell Santner", "AR", 8.5),
        ("Deepak Chahar", "BOWL", 9.0),
        ("Shardul Thakur", "AR", 8.5),
        ("Corbin Bosch", "AR", 8.0),
        ("Hardik Pandya", "AR", 10.0),
        ("Jasprit Bumrah", "BOWL", 10.0),
        ("Ryan Rickelton", "WK", 8.5),
        ("Will Jacks", "AR", 9.0),
        ("Mayank Rawat", "AR", 7.5),
        ("Mayank Markande", "BOWL", 8.5),
        ("Sherfane Rutherford", "BAT", 8.5),
        ("Raghu Sharma", "BOWL", 7.5),
        ("Atharva Ankolekar", "BOWL", 7.5),
        ("Tilak Varma", "BAT", 9.0),
        ("Ashwani Kumar", "BOWL", 7.5),
        ("Raj Bawa", "AR", 8.0),
        ("Danish Malewar", "BAT", 7.5),
        ("Robin Minz", "WK", 8.0),
        ("Allah Ghazanfar", "BOWL", 8.0),
        ("Naman Dhir", "AR", 8.5),
        ("Mohammed Salahuddin Izhar", "BOWL", 7.5)
    ],
    "KKR": [
        ("Ajinkya Rahane", "BAT", 8.5),
        ("Manish Pandey", "BAT", 8.5),
        ("Sunil Narine", "AR", 10.0),
        ("Rahul Tripathi", "BAT", 8.5),
        ("Tim Seifert", "WK", 8.0),
        ("Navdeep Saini", "BOWL", 8.5),
        ("Rinku Singh", "BAT", 9.5),
        ("Rovman Powell", "BAT", 8.5),
        ("Sarthak Ranjan", "BAT", 7.5),
        ("Finn Allen", "WK", 8.5),
        ("Rachin Ravindra", "AR", 9.5),
        ("Cameron Green", "AR", 9.5),
        ("Ramandeep Singh", "BAT", 8.5),
        ("Anukul Roy", "AR", 8.0),
        ("Varun Chakaravarthy", "BOWL", 9.5),
        ("Kartik Tyagi", "BOWL", 8.5),
        ("Blessing Muzarabani", "BOWL", 8.5),
        ("Prashant Solanki", "BOWL", 8.0),
        ("Matheesha Pathirana", "BOWL", 9.5),
        ("Saurabh Dubey", "BOWL", 7.5),
        ("Vaibhav Arora", "BOWL", 8.5),
        ("Umran Malik", "BOWL", 8.5),
        ("Angkrish Raghuvanshi", "BAT", 8.0),
        ("Tejasvi Singh", "WK", 7.5),
        ("Daksh Kamra", "AR", 7.5)
    ],
    "RR": [
        ("Ravindra Jadeja", "AR", 10.0),
        ("Sandeep Sharma", "BOWL", 9.0),
        ("Adam Milne", "BOWL", 8.5),
        ("Donovan Ferreira", "WK", 8.0),
        ("Dasun Shanaka", "AR", 8.5),
        ("Jofra Archer", "BOWL", 9.5),
        ("Shimron Hetmyer", "BAT", 9.0),
        ("Tushar Deshpande", "BOWL", 8.5),
        ("Nandre Burger", "BOWL", 8.5),
        ("Riyan Parag", "AR", 9.5),
        ("Yashasvi Jaiswal", "BAT", 10.0),
        ("Kuldeep Sen", "BOWL", 8.0),
        ("Ravi Bishnoi", "BOWL", 9.0),
        ("Dhruv Jurel", "WK", 9.0),
        ("Sushant Mishra", "BOWL", 7.5),
        ("Yudhvir Singh", "BOWL", 8.0),
        ("Shubham Dubey", "BAT", 8.0),
        ("Vignesh Puthur", "AR", 7.5),
        ("Aman Rao", "BAT", 7.5),
        ("Kwena Maphaka", "BOWL", 8.0),
        ("Yash Punja", "AR", 7.5),
        ("Lhuan-dre Pretorius", "WK", 7.5),
        ("Vaibhav Sooryavanshi", "BAT", 7.5),
        ("Ravi Singh", "WK", 7.5),
        ("Brijesh Sharma", "AR", 7.5)
    ],
    "CSK": [
        ("MS Dhoni", "WK", 10.0),
        ("Akeal Hosein", "BOWL", 8.5),
        ("Shreyas Gopal", "AR", 8.0),
        ("Jamie Overton", "AR", 8.5),
        ("Matt Henry", "BOWL", 8.5),
        ("Sanju Samson", "WK", 9.5),
        ("Matt Short", "AR", 8.5),
        ("Sarfaraz Khan", "BAT", 8.0),
        ("Khaleel Ahmed", "BOWL", 8.5),
        ("Shivam Dube", "AR", 9.5),
        ("Ruturaj Gaikwad", "BAT", 10.0),
        ("Rahul Chahar", "BOWL", 8.5),
        ("Spencer Johnson", "BOWL", 9.0),
        ("Mukesh Choudhary", "BOWL", 8.0),
        ("Urvil Patel", "WK", 7.5),
        ("Aman Hakim Khan", "AR", 7.5),
        ("Anshul Kamboj", "BOWL", 8.5),
        ("Noor Ahmad", "BOWL", 9.0),
        ("Dewald Brevis", "BAT", 8.0),
        ("Gurjapneet Singh", "BOWL", 7.5),
        ("Zakary Foulkes", "AR", 7.5),
        ("Prashant Veer", "AR", 7.5),
        ("Ramakrishna Ghosh", "BOWL", 7.5),
        ("Ayush Mhatre", "BAT", 7.5),
        ("Kartik Sharma", "WK", 7.5)
    ],
    "PBKS": [
        ("Marcus Stoinis", "AR", 9.5),
        ("Yuzvendra Chahal", "BOWL", 9.5),
        ("Shashank Singh", "BAT", 9.0),
        ("Praveen Dubey", "BOWL", 8.0),
        ("Lockie Ferguson", "BOWL", 8.5),
        ("Shreyas Iyer", "BAT", 9.5),
        ("Ben Dwarshuis", "BOWL", 8.0),
        ("Vishnu Vinod", "WK", 8.0),
        ("Xavier Bartlett", "BOWL", 8.5),
        ("Yash Thakur", "BOWL", 8.5),
        ("Azmatullah Omarzai", "AR", 8.5),
        ("Vyshak Vijay Kumar", "BOWL", 8.0),
        ("Arshdeep Singh", "BOWL", 9.5),
        ("Marco Jansen", "AR", 9.0),
        ("Nehal Wadhera", "AR", 8.5),
        ("Prabhsimran Singh", "WK", 8.5),
        ("Harpreet Brar", "AR", 8.5),
        ("Priyansh Arya", "BAT", 7.5),
        ("Suryansh Shedge", "BAT", 7.5),
        ("Cooper Connolly", "AR", 8.0),
        ("Mitchell Owen", "AR", 7.5),
        ("Pyla Avinash", "BAT", 7.5),
        ("Harnoor Singh", "BAT", 7.5),
        ("Musheer Khan", "AR", 8.0),
        ("Vishal Nishad", "BOWL", 7.5)
    ],
    "GT": [
        ("Ishant Sharma", "BOWL", 8.5),
        ("Jos Buttler", "WK", 10.0),
        ("Jason Holder", "AR", 8.5),
        ("Jayant Yadav", "BOWL", 8.0),
        ("Kagiso Rabada", "BOWL", 9.5),
        ("Rahul Tewatia", "AR", 8.5),
        ("Luke Wood", "BOWL", 8.0),
        ("Shahrukh Khan", "BAT", 8.5),
        ("Glenn Phillips", "AR", 9.0),
        ("Prasidh Krishna", "BOWL", 8.5),
        ("Rashid Khan", "BOWL", 10.0),
        ("Mohammed Siraj", "BOWL", 9.5),
        ("Washington Sundar", "AR", 8.5),
        ("Sai Kishore", "BOWL", 8.5),
        ("Shubman Gill", "BAT", 10.0),
        ("Tom Banton", "WK", 8.5),
        ("Kulwant Khejroliya", "BOWL", 7.5),
        ("Anuj Rawat", "WK", 8.0),
        ("Sai Sudharsan", "BAT", 9.0),
        ("Manav Suthar", "BOWL", 8.0),
        ("Kumar Kushagra", "WK", 7.5),
        ("Arshad Khan", "BOWL", 7.5),
        ("Nishant Sindhu", "AR", 8.0),
        ("Gurnoor Brar", "BOWL", 7.5),
        ("Ashok Sharma", "BOWL", 7.5)
    ],
    "LSG": [
        ("Mitchell Marsh", "AR", 9.0),
        ("Mohammed Shami", "BOWL", 9.5),
        ("Shahbaz Ahmed", "AR", 8.5),
        ("Anrich Nortje", "BOWL", 9.0),
        ("Nicholas Pooran", "WK", 10.0),
        ("Aiden Markram", "AR", 9.0),
        ("Avesh Khan", "BOWL", 8.5),
        ("Wanindu Hasaranga", "AR", 9.5),
        ("Himmat Singh", "BAT", 8.0),
        ("Matthew Breetzke", "BAT", 8.0),
        ("Rishabh Pant", "WK", 10.0),
        ("Josh Inglis", "WK", 9.0),
        ("M Siddharth", "BOWL", 8.0),
        ("Mohsin Khan", "BOWL", 8.5),
        ("Ayush Badoni", "BAT", 8.5),
        ("Arjun Tendulkar", "BOWL", 7.5),
        ("Akash Singh", "BOWL", 7.5),
        ("Abdul Samad", "BAT", 8.0),
        ("Arshin Kulkarni", "AR", 7.5),
        ("Naman Tiwari", "BOWL", 7.5),
        ("Akshat Raghuwanshi", "BAT", 7.5),
        ("Mayank Yadav", "BOWL", 9.0),
        ("M-Choudhary", "WK", 7.5),
        ("Prince Yadav", "BOWL", 7.5),
        ("Digvesh Rathi", "BOWL", 7.5)
    ],
    "DC": [
        ("David Miller", "BAT", 9.5),
        ("Mitchell Starc", "BOWL", 9.5),
        ("Dushmantha Chameera", "BOWL", 8.5),
        ("KL Rahul", "WK", 10.0),
        ("Karun Nair", "BAT", 8.0),
        ("Axar Patel", "AR", 9.5),
        ("Ben Duckett", "WK", 8.5),
        ("Kuldeep Yadav", "BOWL", 9.5),
        ("Nitish Rana", "BAT", 8.5),
        ("Kyle Jamieson", "BOWL", 8.5),
        ("Lungi Ngidi", "BOWL", 8.5),
        ("T. Natarajan", "BOWL", 9.0),
        ("Mukesh Kumar", "BOWL", 8.5),
        ("Pathum Nissanka", "BAT", 9.0),
        ("Ajay Mandal", "AR", 7.5),
        ("Prithvi Shaw", "BAT", 8.5),
        ("Ashutosh Sharma", "BAT", 8.5),
        ("Auqib Nabi", "BOWL", 7.5),
        ("Sameer Rizvi", "BAT", 8.0),
        ("Tristan Stubbs", "BAT", 9.0),
        ("Abishek Porel", "WK", 8.0),
        ("Vipraj Nigam", "AR", 7.5),
        ("Tripurana Vijay", "BOWL", 7.5),
        ("Sahil Parakh", "BAT", 7.5),
        ("Madhav Tiwari", "AR", 7.5)
    ]
}

ALL_PLAYERS = []
def build_players():
    for team, players in SQUADS.items():
        for p in players:
            name, role, creds = p
            p_id = f"{team.lower()}_{name.lower().replace(' ', '_')}"
            ALL_PLAYERS.append({
                "id": p_id,
                "name": name,
                "team": team,
                "role": role,
                "credits": creds
            })

build_players()
